language: node_js
sudo: required
dist: trusty
node_js:
  - '10.13.0'

branches:
  only:
    - master

addons:
  chrome: stable
    
cache:
  directories:
  - node_modules

install:
- npm install
- npm install -g @angular/cli

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - "export DISPLAY=:99.0"

scripts:
  - yarn lint
  - yarn build --base-href https://Laura-Weber.github.io/testTravis/
