language: node_js
sudo: false
dist: trusty
node_js:
  - '10.13.0'

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
    
cache:
  directories:
  - "./node_modules"

install:
- npm install
- npm install -g @angular/cli

scripts:
- yarn lint
- yarn build --base-href https://Laura-Weber.github.io/testTravis/
