language: node_js
sudo: false
dist: trusty
node_js:
  - '10.13.0'

branches:
  only:
    - master
    
cache:
  directories:
  - "./node_modules"

install:
- npm install
- npm install -g @angular/cli

scripts:
- yarn lint
- yarn build --base-href https://Laura-Weber.github.io/testTravis/
