language: node_js
sudo: false
dist: trusty
node_js:
  - '10.13.0'

branches:
  only:
    - master

addons:
  chrome: stable
    
cache:
  directories:
  - node_modules

install:
- npm install
- npm install -g @angular/cli

before_script:
- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
- export CHROME_BIN=chromium-browser

scripts:
- yarn lint
- yarn build --base-href https://Laura-Weber.github.io/testTravis/
